function loadAllItems() {
    return [
        {
            number:0,
            lcdNumber:['._.','|.|','|_|']
        },
        {
            number:1,
            lcdNumber:['...','..|','..|']
        },
        {
            number:2,
            lcdNumber:['._.','._|','|_.']
        },
        {
            number:3,
            lcdNumber:['._.','._|','._|']
        },
        {
            number:4,
            lcdNumber:['...','|_|','..|']
        },
        {
            number:5,
            lcdNumber:['._.','|_.','._|']
        },
        {
            number:6,
            lcdNumber:['._.','|_.','|_|']
        },
        {
            number:7,
            lcdNumber:['._.','..|','..|']
        },
        {
            number:8,
            lcdNumber:['._.','|_|','|_|']
        },
        {
            number:9,
            lcdNumber:['._.','|_|','..|']
        }
    ];
}

